openapi: 3.0.3
info:
  title: WATER
  version: 1.0.0
  description: WATER
  servers:
  - url: http://localhost:8080/water_war
    description: Server
paths:
  /login:
    post:
      summary: LogIn User
      tags:
        - getters
      requestBody:
        required: true
        description: User to logIn
        content:
          application/json:
            schema:
              type: string
              example: null
      responses:
        "999":
          description: error on client side
        "200":
          description: successful receipt of id
          content:
            application/json:
              schema:
                type: string
                example: null
  /getCooler:
    get:
      summary: Cooler get method
      tags:
        - getters
      responses:
        "999":
          description: error on client side
        "200":
          description: successful receipt of cooler
          content:
            application/json:
              schema:
                type: object
                example: null
  /getCpu:
    get:
      summary: CPU get method
      tags:
        - getters
      responses:
        "999":
          description: error on client side
        "200":
          description: successful receipt of CPU
          content:
            application/json:
              schema:
                type: object
                example: null
  /getSSD:
    get:
      summary: SSD get method
      tags:
        - getters
      responses:
        "999":
          description: error on client side
        "200":
          description: successful receipt of SSD
          content:
            application/json:
              schema:
                type: object
                example: null
  /getHDD:
    get:
      summary: HDD get method
      tags:
        - getters
      responses:
        "999":
          description: error on client side
        "200":
          description: successful receipt of HDD
          content:
            application/json:
              schema:
                type: object
                example: null
  /getMotherboard:
    get:
      summary: Motherboard get method
      tags:
        -   getters
      responses:
        "999":
          description: error on client side
        "200":
          description: successful receipt of motherboard
          content:
            application/json:
              schema:
                type: object
                example: null
  /getPowerSupply:
    get:
      summary: Powersupply get method
      tags:
        - getters
      responses:
        "999":
          description: error on client side
        "200":
          description: successful receipt of powersupply
          content:
            application/json:
              schema:
                type: object
                example: null
  /getUserId:
    get:
      summary: User id get method
      tags:
        - getters
      responses:
        "999":
          description: error on client side
        "200":
          description: successful receipt of user id
          content:
            application/json:
              schema:
                type: integer
                example: 0
  /setId:
    post:
      summary: Id set method
      tags:
        - setters
      requestBody:
        required: true
        description: id to set, watch example
        content:
          application/json:
            schema:
              type: integer
              example: {id: 2}
      responses:
        "999":
          description: error on client side
        "200":
          description: empty