openapi: 3.0.3
info:
  title: WATER
  version: 1.0.0
  description: WATER
servers:
  - url: http://localhost:8080/water_war
    description: Server
paths:
  /login:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                userpassword:
                  type: string
              required:
                - username
                - userpassword
            example:
              username: user2
              userpassword: hash2
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  status:
                    type: string
                  message:
                    type: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type:string
      summary: Login
      description: Logs in a user with a username and password.
  /register:
    get:
      summary: Register user
      tags:
        - getters
      responses:
        "999":
          description: error on client side
        "200":
          description: Register user
          content:
            application/json:
              schema:
                type: string
                example: null
      security:
        - cors: []
  /logout:
    get:
      summary: LogOut user
      tags:
        - getters
      responses:
        "999":
          description: error on client side
        "200":
          description: Logout user
          content:
            application/json:
              schema:
                type: string
                example: null
      security:
        - cors: []
  /chats:
    get:
      summary: Get user's chats
      tags:
        - getters
      responses:
        "999":
          description: error on client side
        "200":
          description: Chats got
          content:
            application/json:
              schema:
                type: string
                example: null
      security:
        - cors: []
  /chat:
    get:
      summary: Get chat's messages
      tags:
        - getters
      responses:
        "999":
          description: error on client side
        "200":
          description: Messages got
          content:
            application/json:
              schema:
                type: string
                example: null
      security:
        - cors: []

securitySchemes:
  cors:
    type: apiKey
    name: Access-Control-Allow-Origin
    in: header